version: "3.9"
services:
    frontend:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - backend
    
    backend:
        image: postgres
        volumes:
            - ./mounts/db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
